[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # hybrid
repo = 'w0ng/vim-hybrid'

[[plugins]] # Toml
repo  = 'cespare/vim-toml'

[[plugins]] # Japanese doc
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
    set helplang=ja,en
'''

[[plugins]] # colorschema
repo = 'tomasr/molokai'

[[plugins]] # indent
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]] # space
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'neomake/neomake'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
